name: Deploy Laravel App

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP and Composer
        run: |
          sudo apt-get update
          sudo apt-get install -y php php-cli php-mbstring unzip
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer

      - name: Install Dependencies and Build
        run: |
          composer install --no-interaction --no-dev --optimize-autoloader
          cp .env.example .env
          php artisan key:generate

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@172.31.32.134 "cd /home/ubuntu/your-laravel-app && git pull origin main && composer install --no-interaction --no-dev && php artisan migrate"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.YOUR_SECRET_NAME }}  # Replace with the name of your secret
